### PR TITLE
support GHC 8.8

### PR DESCRIPTION
**Pull request by skogsbaer**

### CODE REVIEW

**Comment by skogsbaer** [comment]
@hvr could you please merge this PR? If you like, I could upload the new version to hackage.

**Comment by neongreen** [comment]
https://github.com/awakesecurity/proto3-suite depends on this as well. It would be lovely to have a new version released.

**Comment by hvr** [comment]
Thanks; I'll deal with this asap (over the weekend -- btw, I github notifications are not a reliable way to get my attention; if you need something done, feel free to drop me an email to my gmail addr or msg me on discord)

**Comment by hvr** [comment]
Duplicate of #7

**Pull request closed without merging**
