### PR TITLE
Allow happy-1.20

### PR DESCRIPTION
**Pull request by tvh**

### CODE REVIEW

**Comment by skogsbaer** [comment]
Is there anything that prevents this PR from being merged? It prevents other packages to become compatible with GHC 8.10

**Comment by andreasabel** [comment]
Would fix #13.

**Comment by andreasabel** [comment]
Please, haskell-janitors, merge this PR for Chrstmas!

@basvandijk
Bas van Dijk basvandijk
@dmwit
Daniel Wagner dmwit
@erikd
Erik de Castro Lopo erikd
@ivan-m
Ivan Lazar Miljenovic ivan-m
@JohnLato
John Lato JohnLato
@kfish
Conrad Parker kfish
@nh2
Niklas Hambüchen nh2
@silky
Noon van der Silk silky
@simonmichael
Simon Michael simonmichael
@sordina
Lyndon Maydwell sordina

**Comment by nh2** [comment]
Looks good to me.

**Comment by nh2** [comment]
FYI, I can merge but I cannot upload to Hackage (I think when we made `haskell-pkg-janitors`, we took care of the org only on Github, not Hackage).

**Comment by skogsbaer** [comment]
Is there any chance that we get the new version on hackage in 2021? Please...

@basvandijk
Bas van Dijk basvandijk
@dmwit
Daniel Wagner dmwit
@erikd
Erik de Castro Lopo erikd
@ivan-m
Ivan Lazar Miljenovic ivan-m
@JohnLato
John Lato JohnLato
@kfish
Conrad Parker kfish
@nh2
Niklas Hambüchen nh2
@silky
Noon van der Silk silky
@simonmichael
Simon Michael simonmichael
@sordina
Lyndon Maydwell sordina

**Comment by andreasabel** [comment]
@nh2 See https://wiki.haskell.org/Taking_over_a_package

> * The current maintainer can do it directly on the package maintainer group page on hackage: http://hackage.haskell.org/package/<package>/maintainers/
> You will need to tell them your hackage username. They simply follow the "edit" link and add your username to the group.
> OR
> * The current maintainer can email the Hackage administrators (admin@hackage.haskell.org), saying s/he wants you to take over the package, or at least wants you to be allowed to upload new versions.

Maybe the easiest is that you @nh2 ask the Hackage administrators to get upload permission if it is too difficult to get the attention of the one with the upload permission.

**Comment by andreasabel** [comment]
The current list of uploaders is https://hackage.haskell.org/package/haskell-src/maintainers/

 - ConradParker
 - DonaldStewart
 - HerbertValerioRiedel
 - IanLynagh
 - RossPaterson

Please add me (AndreasAbel) to the list of uploaders, @hvr.

**Comment by nh2** [comment]
> Maybe the easiest is that you @nh2 ask the Hackage administrators to get upload permission if it is too difficult to get the attention of the one with the upload permission.

I don't want to become maintainer of `haskell-src`; I'm not a user of this package. I'm just a `haskell-pkg-janitor` in this case.

> Please add me (AndreasAbel) to the list of uploaders, @hvr.

:+1:

**Comment by andreasabel** [comment]
@hvr @nh2  I volunteer to maintain `haskell-src` and host it on my github account.
If I get your blessings, I will do this.
If you want to keep it at `haskell-pkg-janitors`, please add me to this organization and allow me to maintain `haskell-src` here.  (But I have no interest in the other, anyway dormant packages.)

In any case, something has to happen fast now, we are past 100 days after this PR was submitted.

**Comment by skogsbaer** [comment]
@andreasabel do you have upload rights for haskell-src now? If not, I will now create a fork and use the forked package.

**Comment by andreasabel** [comment]
Horray, finally I got the upload rights and released revisions of 1.0.3.0 and 1.0.3.1 that build with happy-1.20!
Phew!

**Pull request merged**
